### ISSUE TITLE
StandardApi::Orders throwing ActionController::UnpermittedParameters error

### ISSUE THREAD

**Issue by briankung** [waratuman/standardapi#30]
Sentry link: https://sentry.io/organizations/42floors/issues/1177753317/?project=1316485&query=is%3Aunresolved&statsPeriod=14d

Per the Sentry log, [this code](https://github.com/waratuman/standardapi/blob/master/lib/standard_api/orders.rb#L32) is throwing the `ActionController::UnpermittedParameters` error:

```rb
# def self.sanitize(orders, permit)

#    stuff

#    case orders
#    when Hash, ActionController::Parameters
#      orders.each do |key, value|
#       if key.to_s.count('.') == 1
#         ...
#       else
        raise(ActionController::UnpermittedParameters.new([orders]))
#       end
#     end
#   end
# end
``` 

I think it would be appropriate to do check on the config, as per `includes.rb`: https://github.com/waratuman/standardapi/blob/master/lib/standard_api/includes.rb#L64

However, `includes.rb` checks a config named `Rails.configuration.action_on_unpermitted_includes`. Is that correct? The [rails standard](https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-permit) is `Rails.application.config.action_controller.action_on_unpermitted_parameters`

**Comment by waratuman** [comment]
Ah, so yes, `Rails.application.config.action_controller.action_on_unpermitted_parameters` is the correct call (but I think the other works as well). By default though, standardapi will raise and error. We default to having things need to be explicitly set in the parameters. So for the sentry error the best thing to do would be to update the `availabilties_acl.rb` to include what you are tying to oder.

**Comment by waratuman** [comment]
This [commit](https://github.com/waratuman/standardapi/commit/084ce708159c7fc968424bd289ee846062d98561) should resolve.
