### ISSUE TITLE
Method for implicitly scoping REST request to user records

### ISSUE THREAD

**Issue by calebfaruki** [waratuman/standardapi#41]
I was thinking of a helpful method in case you want to scope data in an API request to an API key or user account implicitly.

```rb
class ExamplesController < ApplicationController
   def model_scopes
      accounts = Arel::Table.new :accounts
      model.class.arel_table[:account_id].eq(accounts[:id])
   end
end
```

What do you think @waratuman ?

**Comment by waratuman** [comment]
I think this is already accomplished via the `current_mask` function. I think the readme already has an example, and you can also look in MLS or Mainframe for examples. The mast can just be generated based on any available information at the time (the current user, the current api key, etc.)

**Comment by calebfaruki** [comment]
So it is. Tested it out. It only works if you specify the `current_mask` as a hash with indifferent key access. Should make a note of that in the docs.

https://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html

```rb
def current_mask
  @current_mask = { references: { subject_id: 1 } }.with_indifferent_access 
end
```

Alternatively, we could update standardapi to use symbols for key lookups by default.

https://github.com/waratuman/standardapi/blob/master/lib/standard_api/controller.rb#L220

**Comment by malomalo** [comment]
@waratuman Do you think this should this be converted to  hash with indifferent access, or use `model.table_name.to_sym`?

**Comment by waratuman** [comment]
I think it should be hash with indifferent access. I guess that may not be reasonable though and we could lookup both by string and failing that lookup by symbol? So it would be `current_mask[model.table_name] || current_mask[model.table_name.to_sym]`.

Thoughts @malomalo @calebfaruki

**Comment by malomalo** [comment]
I think I like the `||` solution

**Comment by calebfaruki** [comment]
No opinion here. No insight into the risk of using indifferent access on a hash. Would be interested in learning however!

**Comment by waratuman** [comment]
9a02bcdf1bbe101dd068ff5b106b1974313c3459 resolves
