### ISSUE TITLE
Better documentation for ACL on HABTM

### ISSUE THREAD

**Issue by calebfaruki** [waratuman/standardapi#54]
It's not clear in the docs how to handle setting HABTM associations via POST.

```rb
module BuildingACL
  def attributes
    [
      {region_ids: []},
    ]
  end

  def nested
    [
      :regions
    ]
  end
end
```

```rb
class Building < ApplicationRecord
  has_and_belongs_to_many :regions

  accepts_nested_attributes_for :regions
end
```

```json
{
  "region_ids": ["fdsafdsa-fdsa-fdsa-fds-fdsafdsafdsa"]
}
```

This doesn't seem to work. Any tips?

**Comment by calebfaruki** [comment]
Ugh, the issue is you have to nest the request body:

```json
{
  "building": {
    "region_ids": ["..."]
  }
}
```

**Comment by malomalo** [comment]
If you don't want to do this you can use [ActionController::ParamsWrapper](https://api.rubyonrails.org/v6.1.4/classes/ActionController/ParamsWrapper.html), the initializer is located in `config/initializers/wrap_parameters.rb`.

I also wonder if we should follow the `include_root_in_json` config in our responses if it's easy. But for another day

**Comment by calebfaruki** [comment]
Brevity is nice but it's not so nice that it's worth overriding the default behavior of the params wrapper. My vote is that we just post some examples for `belongs_to`, `has_many` and `has_and_belongs_to_many` with accompanying ACL examples and request bodies. @malomalo
