### ISSUE TITLE
Order parameter should be renamed or made configurable

### ISSUE THREAD

**Issue by calebfaruki** [waratuman/standardapi#79]
`Order` works in StandardAPI context as a verb. But it because it's valid as a noun for ecommerce applications:

```rb
StandardAPI::Includes.sanitize({ order: true }, { order: true })
# lib/standard_api/includes.rb:81:in `sanitize': undefined method `each' for nil:NilClass (NoMethodError)
#
#      includes.each do |k, v|
#              ^^^^^
#  from lib/standard_api/includes.rb:83:in `block in sanitize'
#  from lib/standard_api/includes.rb:81:in `each'
#  from lib/standard_api/includes.rb:81:in `sanitize'
```

Here is why `includes` becomes nil:

```rb
# This error is caused by the following behavior:
StandardAPI::Includes.normalize({ order: true })
=> {"order"=>nil}
# But ideally, the behavior should be this:
irb(main):023> StandardAPI::Includes.normalize({ order: true })
=> {"order"=>{}}
```

For this reason, the `order` parameter key should either be renamed to an unambiguous verb like `sort` or the term `order` should be configurable at the query parameter level so that it is delegated to the underlying order logic.

I personally prefer a full rename because mirrors `include` semantically. Order is very often used as a noun. Rails uses the term `order` to disambiguate from the array sort method and because the term `order` corresponds to the SQL command. But at the API layer, the client shouldn't care if the record set is sorted by the database or in-memory.

**Comment by waratuman** [comment]
https://github.com/waratuman/standardapi/pull/81
